[project]
name = "yubikey-mcp-hello-world"
version = "0.1.0"
description = "Hello World YubiKey MCP Server"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.2.0",
    "yubikey-manager>=5.0.0",
]

[project.scripts]
yubikey-mcp-hello = "server:main"
